import type { Params } from '../store/paramSchema'

/**
 * Yerleşik presetler.
 *
 * Her preset TAM bir görünümdür: uygulanırken önce varsayılanlara dönülür,
 * sonra buradaki alanlar yazılır. Böylece preset'ler birbirinin artığını
 * taşımaz (üstüste binmiş ayarlar en sık karşılaşılan "neden böyle görünüyor"
 * kaynağıdır).
 */
export interface Preset {
  id: string
  name: string
  hint: string
  category: PresetCategory
  params: Partial<Params>
}

export const PRESET_CATEGORIES = [
  { id: 'surveillance', label: 'GÖZETİM' },
  { id: 'terminal', label: 'TERMİNAL / CRT' },
  { id: 'minimal', label: 'MİNİMAL' },
  { id: 'y2k', label: 'Y2K / CHROME' },
  { id: 'military', label: 'ASKERİ / IR' },
  { id: 'data', label: 'VERİ' },
  { id: 'glitch', label: 'GLITCH' },
  { id: 'art', label: 'SİNEMATİK' },
  { id: 'user', label: 'KENDİ PRESETLERİM' },
] as const

export type PresetCategory = (typeof PRESET_CATEGORIES)[number]['id']

export const BUILTIN_PRESETS: Preset[] = [
  /* ── GÖZETİM ────────────────────────────────────────────────────────── */
  {
    id: 'surveillance',
    name: 'Surveillance',
    hint: 'CCTV · timecode · REC',
    category: 'surveillance',
    params: {
      colorMode: 'single',
      accentColor: '#e8e8e8',
      boxStyle: 'corners',
      cornerLength: 0.2,
      boxStrokeWidth: 2,
      boxPadding: 10,
      crosshair: true,
      crosshairExtend: 0.06,
      centroidDot: 2,
      labelEnabled: true,
      labelTemplate: '{id} [{x},{y}]',
      labelPosition: 'top-left',
      labelSize: 13,
      labelBackground: 0.45,
      backgroundSaturation: 0.15,
      hudCorners: true,
      hudTimecode: true,
      hudFrameNumber: true,
      hudBlobCount: true,
      hudRecDot: true,
      hudText: 'CAM 01',
      scanlines: 0.18,
      vignette: 0.35,
      filmGrain: 0.22,
      persistence: 20,
    },
  },
  {
    id: 'cctv-grid',
    name: 'CCTV Grid',
    hint: 'ızgara · küçük kutular · yoğun HUD',
    category: 'surveillance',
    params: {
      colorMode: 'single',
      accentColor: '#d8dde3',
      boxStyle: 'full',
      boxStrokeWidth: 1,
      boxPadding: 4,
      crosshair: false,
      centroidDot: 1.5,
      labelEnabled: true,
      labelTemplate: '{id}',
      labelPosition: 'top-left',
      labelSize: 10,
      labelBackground: 0.6,
      labelPadding: 2,
      backgroundSaturation: 0,
      backgroundContrast: 1.15,
      hudCorners: true,
      hudTimecode: true,
      hudFrameNumber: true,
      hudBlobCount: true,
      hudSize: 10,
      hudMargin: 14,
      gridAmount: 0.35,
      gridSize: 48,
      scanlines: 0.12,
      vignette: 0.25,
      maxBlobs: 20,
      minArea: 0.03,
    },
  },
  {
    id: 'night-vision',
    name: 'Night Vision',
    hint: 'yeşil gece görüşü · yüksek kazanç',
    category: 'surveillance',
    params: {
      colorMode: 'single',
      accentColor: '#8fff9a',
      brightness: 0.15,
      contrast: 0.2,
      boxStyle: 'corners',
      cornerLength: 0.3,
      boxStrokeWidth: 1.5,
      boxGlow: 8,
      crosshair: true,
      crosshairExtend: 0.15,
      centroidDot: 2,
      labelEnabled: true,
      labelTemplate: '{id}',
      labelSize: 12,
      backgroundMode: 'dimmed',
      backgroundOpacity: 0.85,
      backgroundSaturation: 0,
      maskOverlay: true,
      maskColor: '#3dff6b',
      maskOpacity: 0.18,
      maskBlend: 'screen',
      scanlines: 0.22,
      scanlineSpacing: 3,
      vignette: 0.6,
      filmGrain: 0.45,
      hudTimecode: true,
      hudText: 'NV MODE',
    },
  },
  {
    id: 'perimeter-alert',
    name: 'Perimeter Alert',
    hint: 'kırmızı alarm · yanıp sönen kutu',
    category: 'surveillance',
    params: {
      colorMode: 'single',
      accentColor: '#ff3b30',
      boxStyle: 'full',
      boxStrokeWidth: 2.5,
      boxFill: 0.08,
      boxDash: 'dashed',
      boxDashScale: 1.5,
      boxDashSpeed: 6,
      boxPadding: 8,
      boxPulseAmount: 0.04,
      boxPulseSpeed: 3,
      crosshair: true,
      crosshairExtend: 0.25,
      crosshairGap: 10,
      centroidDot: 0,
      labelEnabled: true,
      labelTemplate: 'ALERT {id}',
      labelPosition: 'top-left',
      labelSize: 13,
      labelBackground: 0.65,
      labelBorder: true,
      backgroundMode: 'dimmed',
      backgroundOpacity: 0.6,
      backgroundSaturation: 0.3,
      hudCorners: true,
      hudRecDot: true,
      hudTimecode: true,
      hudText: 'INTRUSION',
      vignette: 0.45,
    },
  },

  /* ── TERMİNAL / CRT ─────────────────────────────────────────────────── */
  {
    id: 'terminal-green',
    name: 'Terminal Green',
    hint: 'fosfor yeşili · marching ants',
    category: 'terminal',
    params: {
      colorMode: 'single',
      accentColor: '#00ff41',
      boxStyle: 'full',
      boxStrokeWidth: 1.5,
      boxDash: 'dashed',
      boxDashScale: 2,
      boxDashSpeed: 2,
      boxPadding: 8,
      boxGlow: 10,
      crosshair: true,
      crosshairExtend: 1,
      crosshairWidth: 0.5,
      crosshairGap: 14,
      centroidDot: 2,
      labelEnabled: true,
      labelTemplate: 'TRK_{id}\\nA:{area}',
      labelPosition: 'top-right',
      labelSize: 12,
      labelTracking: 1.5,
      maskOverlay: true,
      maskColor: '#00ff41',
      maskOpacity: 0.22,
      maskBlend: 'screen',
      backgroundMode: 'dimmed',
      backgroundOpacity: 0.5,
      backgroundSaturation: 0,
      hudCorners: true,
      hudTimecode: true,
      hudBlobCount: true,
      scanlines: 0.3,
      scanlineSpacing: 3,
      filmGrain: 0.25,
      vignette: 0.4,
      trailLength: 18,
      trailStyle: 'fade',
    },
  },
  {
    id: 'amber-crt',
    name: 'Amber CRT',
    hint: 'kehribar fosfor · ağır scanline',
    category: 'terminal',
    params: {
      colorMode: 'single',
      accentColor: '#ffb000',
      boxStyle: 'corners',
      cornerLength: 0.3,
      boxStrokeWidth: 2,
      boxGlow: 16,
      boxPadding: 10,
      crosshair: true,
      crosshairExtend: 0.5,
      crosshairWidth: 0.75,
      crosshairGap: 12,
      centroidDot: 2.5,
      labelEnabled: true,
      labelTemplate: '{id}:{speed}',
      labelPosition: 'bottom',
      labelSize: 13,
      labelTracking: 2,
      backgroundMode: 'dimmed',
      backgroundOpacity: 0.35,
      backgroundSaturation: 0,
      backgroundContrast: 1.2,
      scanlines: 0.45,
      scanlineSpacing: 4,
      filmGrain: 0.3,
      vignette: 0.55,
      hudCorners: true,
      hudTimecode: true,
      hudBlobCount: true,
      trailLength: 12,
      trailStyle: 'fade',
    },
  },
  {
    id: 'phosphor-trails',
    name: 'Phosphor Trails',
    hint: 'uzun fosfor izleri · karanlık zemin',
    category: 'terminal',
    params: {
      colorMode: 'palette',
      palette: 'terminal-green',
      boxStyle: 'none',
      crosshair: false,
      centroidDot: 3,
      labelEnabled: false,
      backgroundMode: 'black',
      maskOverlay: true,
      maskColor: '#0bff6a',
      maskOpacity: 0.5,
      maskBlend: 'screen',
      trailLength: 90,
      trailStyle: 'ribbon',
      trailWidth: 4,
      trailTaper: 0.9,
      trailOpacity: 0.85,
      trailColorMode: 'track',
      blendMode: 'screen',
      scanlines: 0.2,
      filmGrain: 0.2,
      vignette: 0.5,
      hudTimecode: true,
      persistence: 30,
    },
  },
  {
    id: 'mono-terminal',
    name: 'Mono Terminal',
    hint: 'siyah-beyaz · dizgi hissi',
    category: 'terminal',
    params: {
      colorMode: 'single',
      accentColor: '#ffffff',
      boxStyle: 'full',
      boxStrokeWidth: 1,
      boxDash: 'dotted',
      boxDashScale: 2,
      boxPadding: 6,
      crosshair: false,
      centroidDot: 1.5,
      labelEnabled: true,
      labelTemplate: '[{id}] {x},{y}',
      labelPosition: 'top-left',
      labelSize: 11,
      labelTracking: 1,
      labelBackground: 0.8,
      labelPadding: 3,
      backgroundMode: 'dimmed',
      backgroundOpacity: 0.28,
      backgroundSaturation: 0,
      hudCorners: false,
      hudTimecode: true,
      hudFrameNumber: true,
      hudBlobCount: true,
      hudSize: 11,
      scanlines: 0.15,
    },
  },

  /* ── MİNİMAL ────────────────────────────────────────────────────────── */
  {
    id: 'minimal-white',
    name: 'Minimal White',
    hint: 'ince · sessiz · editoryal',
    category: 'minimal',
    params: {
      colorMode: 'single',
      accentColor: '#ffffff',
      boxStyle: 'corners',
      cornerLength: 0.14,
      boxStrokeWidth: 1,
      boxPadding: 14,
      crosshair: false,
      centroidDot: 0,
      labelEnabled: true,
      labelTemplate: '{id}',
      labelPosition: 'bottom',
      labelSize: 11,
      labelTracking: 3,
      labelOpacity: 0.75,
      hudCorners: false,
      hudTimecode: false,
      hudBlobCount: false,
      smoothing: 0.75,
      spawnDuration: 10,
      fadeOut: 12,
    },
  },
  {
    id: 'clean-corners',
    name: 'Clean Corners',
    hint: 'yalnızca braketler',
    category: 'minimal',
    params: {
      colorMode: 'single',
      accentColor: '#00ff41',
      boxStyle: 'corners',
      cornerLength: 0.25,
      boxStrokeWidth: 2.5,
      boxPadding: 10,
      crosshair: false,
      centroidDot: 0,
      labelEnabled: false,
      hudCorners: false,
      hudTimecode: false,
      hudBlobCount: false,
      smoothing: 0.65,
      spawnDuration: 8,
      fadeOut: 10,
    },
  },
  {
    id: 'hairline',
    name: 'Hairline',
    hint: 'saç teli çizgi · minik nokta',
    category: 'minimal',
    params: {
      colorMode: 'single',
      accentColor: '#ffffff',
      boxStyle: 'circle',
      boxStrokeWidth: 0.5,
      boxOpacity: 0.8,
      boxPadding: 20,
      crosshair: true,
      crosshairExtend: 0.03,
      crosshairWidth: 0.5,
      centroidDot: 1,
      labelEnabled: false,
      backgroundSaturation: 0.6,
      hudCorners: false,
      hudTimecode: false,
      hudBlobCount: false,
      smoothing: 0.8,
      trailLength: 30,
      trailStyle: 'line',
      trailWidth: 0.5,
      trailOpacity: 0.35,
    },
  },
  {
    id: 'ghost',
    name: 'Ghost',
    hint: 'yarı saydam · yumuşak',
    category: 'minimal',
    params: {
      colorMode: 'single',
      accentColor: '#cfd8ff',
      boxStyle: 'capsule',
      boxStrokeWidth: 1.5,
      boxFill: 0.06,
      boxPadding: 18,
      boxGlow: 18,
      crosshair: false,
      centroidDot: 0,
      labelEnabled: true,
      labelTemplate: '{id}',
      labelPosition: 'center',
      labelSize: 22,
      labelOpacity: 0.35,
      backgroundBlur: 6,
      backgroundSaturation: 0.5,
      globalOpacity: 0.7,
      blendMode: 'screen',
      smoothing: 0.85,
      spawnDuration: 14,
      fadeOut: 16,
      hudCorners: false,
      hudTimecode: false,
      hudBlobCount: false,
    },
  },

  /* ── Y2K / CHROME ───────────────────────────────────────────────────── */
  {
    id: 'y2k-chrome',
    name: 'Y2K Chrome',
    hint: 'krom · kapsül · bezier',
    category: 'y2k',
    params: {
      colorMode: 'palette',
      palette: 'y2k',
      boxStyle: 'capsule',
      boxStrokeWidth: 3,
      boxFill: 0.12,
      boxPadding: 12,
      boxGlow: 22,
      boxPulseAmount: 0.03,
      boxPulseSpeed: 1.5,
      crosshair: false,
      centroidDot: 4,
      centroidHollow: true,
      reticle: true,
      reticleRadius: 30,
      reticleSpeed: 0.8,
      reticleTicks: 12,
      labelEnabled: true,
      labelTemplate: '{id}',
      labelPosition: 'center',
      labelSize: 18,
      linkMode: 'nearest-n',
      linkNearestN: 2,
      linkStyle: 'bezier',
      linkWidth: 2,
      linkOpacity: 0.55,
      backgroundMode: 'dimmed',
      backgroundOpacity: 0.7,
      backgroundBlur: 3,
      chromaticAberration: 1.5,
      hudCorners: false,
      hudTimecode: false,
      trailLength: 22,
      trailStyle: 'ribbon',
      trailWidth: 2.5,
      blendMode: 'screen',
    },
  },
  {
    id: 'bubblegum',
    name: 'Bubblegum',
    hint: 'pembe-turkuaz · nefes alan daireler',
    category: 'y2k',
    params: {
      colorMode: 'palette',
      palette: 'hot-pink',
      boxStyle: 'circle',
      boxStrokeWidth: 4,
      boxFill: 0.15,
      boxPadding: 16,
      boxGlow: 26,
      boxPulseAmount: 0.06,
      boxPulseSpeed: 2.2,
      crosshair: false,
      centroidDot: 5,
      labelEnabled: true,
      labelTemplate: '{id}',
      labelPosition: 'center',
      labelSize: 20,
      labelUppercase: true,
      backgroundMode: 'dimmed',
      backgroundOpacity: 0.55,
      backgroundSaturation: 1.5,
      backgroundBlur: 4,
      blendMode: 'screen',
      trailLength: 30,
      trailStyle: 'dots',
      trailWidth: 3,
      hudCorners: false,
      hudTimecode: false,
      hudBlobCount: false,
    },
  },
  {
    id: 'holo',
    name: 'Holo',
    hint: 'gökkuşağı döngüsü · screen blend',
    category: 'y2k',
    params: {
      colorMode: 'rainbow',
      colorCycleSpeed: 1.2,
      boxStyle: 'diamond',
      boxStrokeWidth: 3,
      boxPadding: 14,
      boxGlow: 20,
      crosshair: true,
      crosshairExtend: 0.2,
      crosshairWidth: 1.5,
      centroidDot: 3,
      labelEnabled: true,
      labelTemplate: '{id}',
      labelPosition: 'top-right',
      labelSize: 14,
      linkMode: 'all',
      linkStyle: 'arc',
      linkWidth: 1.5,
      linkOpacity: 0.4,
      backgroundMode: 'dimmed',
      backgroundOpacity: 0.6,
      blendMode: 'screen',
      chromaticAberration: 2,
      trailLength: 24,
      trailStyle: 'fade',
      trailColorMode: 'gradient',
      hudCorners: false,
      hudTimecode: false,
    },
  },

  /* ── ASKERİ / IR ────────────────────────────────────────────────────── */
  {
    id: 'military-ir',
    name: 'Military IR',
    hint: 'termal · hedef kilidi',
    category: 'military',
    params: {
      colorMode: 'by-velocity',
      palette: 'infrared',
      boxStyle: 'full',
      boxStrokeWidth: 2,
      boxFill: 0.1,
      boxPadding: 6,
      boxSquare: true,
      crosshair: true,
      crosshairExtend: 0.45,
      crosshairGap: 20,
      reticle: true,
      reticleRadius: 42,
      reticleSpeed: -1.6,
      reticleTicks: 8,
      velocityVector: true,
      velocityScale: 12,
      labelEnabled: true,
      labelTemplate: 'TGT {id}\\nV:{speed}',
      labelPosition: 'outside-leader',
      labelSize: 13,
      labelBackground: 0.5,
      labelBorder: true,
      backgroundMode: 'posterize',
      posterizeLevels: 5,
      backgroundSaturation: 0.4,
      hudCorners: true,
      hudTimecode: true,
      hudBlobCount: true,
      hudText: 'IR · THERMAL',
      gridAmount: 0.12,
      gridSize: 120,
      vignette: 0.55,
      filmGrain: 0.3,
      persistence: 24,
    },
  },
  {
    id: 'radar-lock',
    name: 'Radar Lock',
    hint: 'dönen halkalar · merkeze bağlantı',
    category: 'military',
    params: {
      colorMode: 'single',
      accentColor: '#7dff5c',
      boxStyle: 'none',
      crosshair: true,
      crosshairExtend: 1,
      crosshairWidth: 0.5,
      crosshairGap: 30,
      centroidDot: 3,
      reticle: true,
      reticleRadius: 56,
      reticleSpeed: 2.4,
      reticleTicks: 16,
      velocityVector: true,
      velocityScale: 16,
      labelEnabled: true,
      labelTemplate: '{id} · {speed}',
      labelPosition: 'follow-corner',
      labelSize: 12,
      linkMode: 'to-center',
      linkStyle: 'straight',
      linkWidth: 1,
      linkOpacity: 0.35,
      linkLabel: true,
      backgroundMode: 'dimmed',
      backgroundOpacity: 0.3,
      backgroundSaturation: 0.1,
      gridAmount: 0.2,
      gridSize: 90,
      hudCorners: true,
      hudTimecode: true,
      hudBlobCount: true,
      hudText: 'LOCK',
      vignette: 0.5,
    },
  },
  {
    id: 'thermal-blob',
    name: 'Thermal Blob',
    hint: 'maske ısı haritası',
    category: 'military',
    params: {
      colorMode: 'by-area',
      palette: 'infrared',
      boxStyle: 'none',
      crosshair: false,
      centroidDot: 0,
      labelEnabled: true,
      labelTemplate: '{area}',
      labelPosition: 'center',
      labelSize: 12,
      labelBackground: 0.4,
      contourMode: 'outline',
      contourWidth: 2,
      contourOpacity: 1,
      contourFill: 0.35,
      backgroundMode: 'dimmed',
      backgroundOpacity: 0.25,
      backgroundSaturation: 0,
      maskOverlay: true,
      maskColor: '#ff3b00',
      maskOpacity: 0.55,
      maskBlend: 'screen',
      fillHoles: 3,
      noiseReduction: 2,
      hudTimecode: true,
      hudBlobCount: true,
      vignette: 0.4,
    },
  },

  /* ── VERİ ───────────────────────────────────────────────────────────── */
  {
    id: 'data-viz',
    name: 'Data Viz',
    hint: 'delaunay ağı · veri etiketleri',
    category: 'data',
    params: {
      colorMode: 'by-area',
      palette: 'cyan-magenta',
      boxStyle: 'none',
      centroidDot: 5,
      crosshair: false,
      labelEnabled: true,
      labelTemplate: '{id} · {area}px · {speed}',
      labelPosition: 'follow-corner',
      labelSize: 12,
      labelBackground: 0.35,
      labelDecimals: 1,
      linkMode: 'delaunay',
      linkWidth: 1,
      linkOpacity: 0.45,
      linkLabel: true,
      linkMidpointDot: 2,
      contourMode: 'hull',
      contourOpacity: 0.5,
      contourWidth: 1,
      backgroundMode: 'dimmed',
      backgroundOpacity: 0.25,
      backgroundSaturation: 0.2,
      hudCorners: false,
      hudTimecode: true,
      hudBlobCount: true,
      trailLength: 40,
      trailStyle: 'dots',
      trailOpacity: 0.5,
      gridAmount: 0.1,
      gridSize: 60,
    },
  },
  {
    id: 'delaunay-net',
    name: 'Delaunay Net',
    hint: 'yalnızca ağ · kutu yok',
    category: 'data',
    params: {
      colorMode: 'by-position',
      boxStyle: 'none',
      crosshair: false,
      centroidDot: 4,
      labelEnabled: false,
      linkMode: 'delaunay',
      linkStyle: 'straight',
      linkWidth: 1.5,
      linkOpacity: 0.7,
      linkMidpointDot: 1.5,
      backgroundMode: 'black',
      blendMode: 'screen',
      trailLength: 0,
      hudCorners: false,
      hudTimecode: false,
      hudBlobCount: true,
      maxBlobs: 24,
      minArea: 0.02,
    },
  },
  {
    id: 'motion-study',
    name: 'Motion Study',
    hint: 'uzun izler · hareket çalışması',
    category: 'data',
    params: {
      colorMode: 'by-velocity',
      palette: 'cyan-magenta',
      boxStyle: 'none',
      crosshair: false,
      centroidDot: 2,
      labelEnabled: false,
      trailLength: 120,
      trailStyle: 'ribbon',
      trailWidth: 3,
      trailTaper: 0.85,
      trailOpacity: 0.9,
      trailColorMode: 'gradient',
      velocityVector: true,
      velocityScale: 10,
      backgroundMode: 'dimmed',
      backgroundOpacity: 0.18,
      backgroundSaturation: 0,
      blendMode: 'screen',
      persistence: 40,
      smoothing: 0.7,
      hudTimecode: true,
      hudBlobCount: true,
    },
  },
  {
    id: 'telemetry',
    name: 'Telemetry',
    hint: 'her şeyi yazan etiketler',
    category: 'data',
    params: {
      colorMode: 'single',
      accentColor: '#9ee7ff',
      boxStyle: 'corners',
      cornerLength: 0.18,
      boxStrokeWidth: 1.5,
      boxPadding: 10,
      crosshair: true,
      crosshairExtend: 0.08,
      centroidDot: 2,
      labelEnabled: true,
      labelTemplate: 'ID {id}\\nXY {x},{y}\\nWH {w}×{h}\\nV {vx},{vy}\\nC {conf}',
      labelPosition: 'outside-leader',
      labelSize: 11,
      labelBackground: 0.6,
      labelBorder: true,
      labelPadding: 4,
      coordSpace: 'pixel',
      backgroundMode: 'dimmed',
      backgroundOpacity: 0.4,
      backgroundSaturation: 0.25,
      hudCorners: true,
      hudTimecode: true,
      hudFrameNumber: true,
      hudBlobCount: true,
      gridAmount: 0.08,
      gridSize: 80,
    },
  },

  /* ── GLITCH ─────────────────────────────────────────────────────────── */
  {
    id: 'glitch-punk',
    name: 'Glitch Punk',
    hint: 'difference blend · jitter',
    category: 'glitch',
    params: {
      colorMode: 'palette',
      palette: 'hot-pink',
      blendMode: 'difference',
      boxStyle: 'diamond',
      boxStrokeWidth: 3,
      boxPadding: 16,
      boxDash: 'dash-dot',
      boxDashSpeed: -8,
      crosshair: true,
      crosshairExtend: 0.9,
      crosshairWidth: 0.5,
      centroidDot: 0,
      labelEnabled: true,
      labelTemplate: '{id}//{x}_{y}',
      labelPosition: 'top-left',
      labelSize: 14,
      labelTracking: -0.5,
      contourMode: 'polygon',
      simplifyEpsilon: 6,
      contourJitter: 4,
      contourWidth: 2,
      backgroundMode: 'pixelate',
      pixelateSize: 8,
      chromaticAberration: 5,
      scanlines: 0.4,
      scanlineSpacing: 6,
      filmGrain: 0.5,
      hudRecDot: true,
      hudText: 'NO SIGNAL',
      trailLength: 8,
      trailStyle: 'line',
      spawnDuration: 2,
    },
  },
  {
    id: 'datamosh',
    name: 'Datamosh',
    hint: 'piksel bloklar · kanal kayması',
    category: 'glitch',
    params: {
      colorMode: 'by-position',
      boxStyle: 'full',
      boxStrokeWidth: 6,
      boxOpacity: 0.7,
      boxFill: 0.2,
      boxPadding: 0,
      boxSquare: true,
      crosshair: false,
      centroidDot: 0,
      labelEnabled: true,
      labelTemplate: '{index}',
      labelPosition: 'center',
      labelSize: 26,
      labelUppercase: true,
      backgroundMode: 'pixelate',
      pixelateSize: 22,
      chromaticAberration: 8,
      blendMode: 'exclusion',
      filmGrain: 0.35,
      scanlines: 0.2,
      hudCorners: false,
      hudTimecode: false,
      hudBlobCount: false,
      spawnDuration: 0,
      fadeOut: 0,
      smoothing: 0.2,
    },
  },
  {
    id: 'scanline-riot',
    name: 'Scanline Riot',
    hint: 'yoğun scanline · titreyen kontur',
    category: 'glitch',
    params: {
      colorMode: 'rainbow',
      colorCycleSpeed: 3,
      boxStyle: 'none',
      crosshair: true,
      crosshairExtend: 1,
      crosshairWidth: 2,
      centroidDot: 0,
      labelEnabled: false,
      contourMode: 'outline',
      contourWidth: 3,
      contourJitter: 7,
      contourOpacity: 1,
      backgroundMode: 'dimmed',
      backgroundOpacity: 0.45,
      backgroundContrast: 1.4,
      blendMode: 'difference',
      scanlines: 0.6,
      scanlineSpacing: 3,
      chromaticAberration: 6,
      filmGrain: 0.4,
      vignette: 0.3,
      hudRecDot: true,
      hudCorners: true,
    },
  },

  /* ── SİNEMATİK ──────────────────────────────────────────────────────── */
  {
    id: 'silhouette',
    name: 'Silhouette',
    hint: 'yalnızca maske · video yok',
    category: 'art',
    params: {
      colorMode: 'single',
      accentColor: '#ffffff',
      backgroundMode: 'maskColored',
      maskColor: '#f2f2f2',
      boxStyle: 'none',
      crosshair: false,
      centroidDot: 0,
      labelEnabled: true,
      labelTemplate: '{id}',
      labelPosition: 'bottom',
      labelSize: 12,
      labelTracking: 4,
      fillHoles: 3,
      noiseReduction: 2,
      hudCorners: false,
      hudTimecode: false,
      hudBlobCount: false,
      vignette: 0.35,
      filmGrain: 0.15,
    },
  },
  {
    id: 'neon-outline',
    name: 'Neon Outline',
    hint: 'parlayan dış çizgi',
    category: 'art',
    params: {
      colorMode: 'palette',
      palette: 'cyan-magenta',
      boxStyle: 'none',
      crosshair: false,
      centroidDot: 0,
      labelEnabled: false,
      contourMode: 'outline',
      contourWidth: 3,
      contourOpacity: 1,
      contourFill: 0.05,
      backgroundMode: 'dimmed',
      backgroundOpacity: 0.2,
      backgroundBlur: 2,
      backgroundSaturation: 0.3,
      blendMode: 'screen',
      globalOpacity: 1,
      trailLength: 20,
      trailStyle: 'fade',
      trailWidth: 2,
      vignette: 0.5,
      hudCorners: false,
      hudTimecode: false,
      hudBlobCount: false,
      fillHoles: 2,
    },
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    hint: 'teknik çizim · ortogonal bağlantı',
    category: 'art',
    params: {
      colorMode: 'single',
      accentColor: '#bcd9ff',
      backgroundMode: 'color',
      backgroundColor: '#0a1a33',
      boxStyle: 'full',
      boxStrokeWidth: 1,
      boxPadding: 12,
      boxDash: 'dashed',
      boxDashScale: 3,
      crosshair: true,
      crosshairExtend: 1,
      crosshairWidth: 0.5,
      centroidDot: 2,
      centroidHollow: true,
      labelEnabled: true,
      labelTemplate: '{id} · {w}×{h}',
      labelPosition: 'top-left',
      labelSize: 11,
      labelTracking: 1,
      linkMode: 'chain',
      linkStyle: 'orthogonal',
      linkWidth: 1,
      linkOpacity: 0.6,
      linkLabel: true,
      gridAmount: 0.3,
      gridSize: 40,
      hudCorners: true,
      hudTimecode: true,
      hudFrameNumber: true,
      hudText: 'FIG. 01',
    },
  },
  {
    id: 'confetti',
    name: 'Confetti',
    hint: 'track başına renk · nokta izleri',
    category: 'art',
    params: {
      colorMode: 'palette',
      palette: 'y2k',
      boxStyle: 'circle',
      boxStrokeWidth: 2,
      boxFill: 0.25,
      boxPadding: 6,
      boxGlow: 12,
      crosshair: false,
      centroidDot: 0,
      labelEnabled: false,
      trailLength: 60,
      trailStyle: 'dots',
      trailWidth: 2.5,
      trailTaper: 0.6,
      trailOpacity: 0.8,
      trailColorMode: 'track',
      backgroundMode: 'dimmed',
      backgroundOpacity: 0.35,
      backgroundBlur: 5,
      blendMode: 'screen',
      maxBlobs: 24,
      minArea: 0.02,
      hudCorners: false,
      hudTimecode: false,
      hudBlobCount: false,
    },
  },
]
